version: '3.8'

services:
  app:
    build: .
    image: ${DOCKER_HUB_USERNAME}/my-nextjs-app:latest
    volumes:
      - .:/app
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/mydb
    depends_on:
      - db
    networks:
      - mynetwork

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '80:80'
    networks:
      - mynetwork

volumes:
  postgres_data:

networks:
  mynetwork:
