name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/my-nextjs-app:latest

    - name: Add SSH key
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}
        

    - name: Add Known Hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts    

    - name: Debug SSH connection
      run: |
        echo "Trying to connect to server..."
        ls -la ~/.ssh
        ssh-add -l
        ssh -o StrictHostKeyChecking=no -v ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} "echo 'Connected successfully!'"

    - name: SSH into server and deploy
      uses: appleboy/ssh-action@v0.1.4
      env:
        SSH_AUTH_SOCK: /tmp/ssh-agent.sock
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          sudo apt update
          sudo apt install -y yarn
          echo "Pulling the latest Docker image..."
          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/my-nextjs-app:latest
          docker-compose down
          docker-compose up -d
          docker-compose exec app yarn migrate